import '../models/token.dart';

final List<Token> dummyTokens = [
  Token(
    fullName: 'DefiGeek Community Japan Token',
    symbol: 'TXJP',
    network: 'eth',
    contract: '0x961dd84059505d59f82ce4fb87d3c09bec65301d',
    imagePath: '',
    websiteUrl: 'https://defigeek.xyz/',
    websiteEnUrl: 'https://defigeek.xyz/en/',
    documentsUrl: 'https://defigeek.xyz/txjp/',
    documentsEnUrl: 'https://defigeek.xyz/en/txjp/',
    xTwitter: 'https://twitter.com/DeFiGeekJapan',
    xTwitterEn: 'https://twitter.com/DeFiGeekJapanEn',
    links: {
      'Dashboard': 'http://dashboard.defigeek.xyz/',
    },
  ),
  Token(
    fullName: 'Yamato DAO Token',
    symbol: 'YMT',
    network: 'eth',
    contract: '',
    imagePath: '',
    websiteUrl: 'https://app.yamato.fi/#/',
    websiteEnUrl: '',
    documentsUrl: 'https://docs.yamato.fi/ymt-yamato-dao-token',
    documentsEnUrl: 'https://docs.yamato.fi/en/ymt-yamato-dao-token',
    xTwitter: 'https://twitter.com/YamatoProtocol',
    xTwitterEn: '',
    links: {},
  ),
  Token(
    fullName: 'Convertible JPY Token',
    symbol: 'CJPY',
    network: 'eth',
    contract: '0x1cfa5641c01406ab8ac350ded7d735ec41298372',
    imagePath: '',
    websiteUrl: 'https://app.yamato.fi/#/',
    websiteEnUrl: '',
    documentsUrl: '',
    documentsEnUrl: '',
    xTwitter: 'https://twitter.com/YamatoProtocol',
    xTwitterEn: '',
    links: {},
  ),
  Token(
    fullName: 'punodwoɔ DAO Token',
    symbol: 'PND',
    network: 'eth',
    contract: '0x5FFF1443Cb859E17e9a6786f7e24c369F22FD002',
    imagePath: '',
    websiteUrl: 'https://pnd.defigeek.xyz/',
    websiteEnUrl: '',
    documentsUrl: 'https://defigeek.gitbook.io/punodwo-document/pnd-pnd-dao-token',
    documentsEnUrl: '',
    xTwitter: '',
    xTwitterEn: '',
    links: {},
  ),
  Token(
    fullName: 'Yamawake DAO Token',
    symbol: 'YMWK',
    network: 'eth',
    contract: '0x15Dac05C93e1c5F31a29547340997BA9f6ec4F87',
    imagePath: '',
    websiteUrl: 'https://yamawake.xyz/',
    websiteEnUrl: '',
    documentsUrl: 'https://docs.yamawake.xyz/readme/ymwk-yamawake-dao-token',
    documentsEnUrl: 'https://docs.yamawake.xyz/english-3/readme/ymwk-yamawake-dao-token',
    xTwitter: '',
    xTwitterEn: '',
    links: {},
  ),
  Token(
    fullName: 'Yabumi DAO Token',
    symbol: '',
    network: 'eth',
    contract: '',
    imagePath: '',
    websiteUrl: 'https://www.yabumi.xyz/',
    websiteEnUrl: 'https://www.yabumi.xyz/en#',
    documentsUrl: 'https://doc.yabumi.xyz/readme/yabumi-dao-token',
    documentsEnUrl: 'https://doc.yabumi.xyz/english/yabumi/yabumi-dao-token',
    xTwitter: '',
    xTwitterEn: '',
    links: {},
  ),
  Token(
    fullName: 'DeFiGeek Community JAPAN DAO Token on Base',
    symbol: 'DFGC',
    network: 'base',
    contract: '0xbc91b74761cae0740f74e42b2673c05146ed810e',
    imagePath: '',
    websiteUrl: 'https://defigeek.xyz/',
    websiteEnUrl: 'https://defigeek.xyz/en/',
    documentsUrl: 'https://verbena-lobe-24a.notion.site/DeFiGeek-Community-JAPAN-DAO-Token-on-Base-DFGC-12c71209d6d7801d9414cf4f30c5ec57',
    documentsEnUrl: '',
    xTwitter: '',
    xTwitterEn: '',
    links: {},
  ),
];

final List<Token> initialTokens = [];
